[package]
name = "obnam"
version = "0.1.0"
authors = ["Lars Wirzenius <liw@liw.fi>"]
edition = "2018"

[dependencies]
anyhow = "1"
bytes = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
structopt = "0.3"
thiserror = "1"
tokio = { version = "0.2", features = ["macros"] }
uuid = { version = "0.8", features = ["v4"] }
warp = { version = "0.2", features = ["tls"] }
