#!/bin/sh
#
# Run the automated tests for the project.

set -eu

quiet=-q
hideok=chronic
if [ "$#" -gt 0 ]
then
    case "$1" in
	verbose | -v | --verbose)
	    quiet=
	    hideok=
	    ;;
    esac
fi

cargo build --all-targets $quiet
cargo clippy $quiet
cargo fmt -- --check
$hideok cargo test $quiet

./format.sh

echo "Everything seems to be in order."
